spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:${random.uuid}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  profiles:
    active: production
releaser:
  git:
    org-name: reactor
    release-train-bom-url: https://github.com/reactor/reactor
    fetch-versions-from-git: true
  gradle:
    build-command: "./gradlew clean bumpVersionsInReadme build publishToMavenLocal --console=plain -PnextVersion={{nextVersion}} -PoldVersion={{oldVersion}} -PcurrentVersion={{version}} {{systemProps}}"

  meta-release:
    release-train-project-name: reactor
    release-train-dependency-names:
      - reactor
    git-org-url: https://github.com/reactor
cf:
  organization: FrameworksAndRuntimes
  space: Reactor
  reactorAppName: projectreactor
  apiHost: api.run.pivotal.io

# Boot values to be passed via env/command line:
# cf.username
# cf.password

# Gradle project properties to be passed to deploy task somehow
# artifactory_publish_contextUrl
# artifactory_publish_repoKey
# artifactory_publish_username
# artifactory_publish_password