:github-tag: master
:org: spring-cloud
:repo: spring-cloud-release-tools
:github-repo: {org}/{repo}
:github-raw: http://raw.github.com/{github-repo}/{github-tag}
:github-code: http://github.com/{github-repo}/tree/{github-tag}
:toc: left
:toclevels: 8
:nofooter:

# Spring Cloud Release Tools

This project can be used to

- update all versions in your Spring Cloud Project according to the Spring Cloud Release setup

== How to run it

Currently we only support running the releaser to update the poms from Java

Go to your project (e.g. Spring Cloud Sleuth)

[source,bash]
----
git clone https://github.com/spring-cloud/spring-cloud-sleuth
cd spring-cloud-sleuth
mkdir -p target
wget http://repo.spring.io/libs-milestone/org/springframework/cloud/internal/spring-cloud-release-tools-spring/1.0.0.M1/spring-cloud-release-tools-spring-1.0.0.M1.jar -O target/spring-cloud-release-tools-spring-1.0.0.M1.jar
java -jar target/spring-cloud-release-tools-spring-1.0.0.M1.jar
----

The application will start running from your working directory.

=== Changing working directory

To change the working directory just run the app with `releaser.workingDir` property.

=== Specifying A Branch

By deafult the releaser will default to using the `master` branch of `spring-cloud-release`.
If you would like to use another branch you can specify it using the `releaser.pom.branch` property.

[source,bash]
----
java -jar target/spring-cloud-release-tools-spring-1.0.0.M1.jar --Dreleaser.pom.branch=Camden.SR6
----

== Future plans
In the future it can also:

- commit the changed values
- perform a release

Other plans:

- add a Maven plugin to perform the work from Maven